### ISSUE TITLE
Error with capture_rtlsdr -b P-GSM -a 23 --bursts /tmp/23.bursts --length 120 --print-bursts

### ISSUE THREAD

**Issue by fe8769a** [romankh/gsm-assessment-toolkit#10]
error with capture_rtlsdr -b P-GSM -a 23 --bursts /tmp/23.bursts --length 120 --print-bursts

ERROR: unhandled exception in Plugin command capture_rtlsdr.
Message was: 

nothing else 

any idea

**Comment by romankh** [comment]
Hi, 

thanks for reporting, I commited a fix for that, please update to the latest git commit and try again

**Comment by romankh** [comment]
Think this is fixed, closing it, please reopen if issue still exists
