### ISSUE TITLE
hello - error when trying to start search

### ISSUE THREAD

**Issue by bourla77** [romankh/gsm-assessment-toolkit#8]
what am i doing wrong
gat > scan_rtlsdr -b GSM900 -g 40
ERROR: unhandled exception in Plugin command scan_rtlsdr.
Message was: arfcn2downlink() takes exactly 1 argument (2 given)

**Comment by romankh** [comment]
you are not doing anything wrong, there was a change in a gr-gsm component
I will try to fix it this weekend

**Comment by bourla77** [comment]
Thanks a lot!
Tal

**Comment by bourla77** [comment]
Is it possible to get BSIC
Of the cell? C2 neighbors cells?

On Oct 4, 2017 14:04, "Tal bourla" <stamshemtal@gmail.com> wrote:

Thanks a lot!
Tal

**Comment by romankh** [comment]
Hi Tal, 

I just pushed a fix for that, try if that helps.
Feedback would be great.
There may be other issues with recent changes of gr-gsm, I will try to investigate this soon.

To answer your question:
No, you dont get BSIC, but you get the cell id CID and location area code LAC for example

**Comment by bourla77** [comment]
Many thanks!!
